@extends("layout")

@section('content')

    <h3> Generate an invoice in XML format </h3>
    <p> Please choose action that you want to do : </p>
    <ul>
    <li><a href="{{ url('fattura/download',$filename) }}">Download Invoice generated</a></li>
    </br>
    <li><a href="{{ url('fattura/mail',$filename) }}">Send Invoice generated by mail</a></li>
</ul>
@endsection
