@extends("layout")

@section('content')

    <h2> Generate an invoice in XML format <em> - step 2 - </em></h2>
    <p> Please check if your invoice is correct : </p>
    <pre style = "border: 1px solid;
                  margin: 5px;
                  padding: 10px;
                  overflow-x: auto;
                  white-space: pre-wrap;
                  word-wrap: break-word;
                  background-color: rgb(226, 234, 241);
                  font-family: Open sans;
                  font-size: 15px;"> {{$content}} </pre>
     <hr>   
    <ul>
        <li> If it isn't correct, <a href="{{ route('invoice-create') }}">go back to form</a></li>
        </br>
        <li> If it's correct 
            <a href="{{ route('invoice-download',$filename) }}">Download Invoice generated</a>
             or 
            <a href="{{ route('writing-mail',$filename) }}">Send Invoice generated by mail</a>
        </li>
        </br>
    </ul>
    <hr>
@endsection
